### ISSUE TITLE
Problem with output format

### ISSUE THREAD

**Issue by overthink** [narutokiran/SortableChallenge#1]
Hi Kiran.

There is a problem with the output produced by your challenge submission.  Could you please make sure each line is a valid JSON document?  e.g. in the following `Canon_PowerShot_A50` should be a string and be quoted.

`{"product_name":Canon_PowerShot_A50,"listings":[{"title":"Canon Power Shot A50 Powershot 0.8MP Digital Camera","manufacturer":"Canon","currency":"USD","price":"64.75"}]}`

Thanks!

Mark from sortable.com

**Comment by viperKiran** [comment]
Hi @overthink, I hope you are doing good. I have solved the bug and double checked the output format. I apologize for the inconvenience caused.
